baseurl = "/"
languageCode = "en-us"
title = "张鹏飞"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "留言"
    url = "/Zguestbook/"
    weight = 5
[[menu.main]]
    name = "行程"
    url = "/schedule.html"
    weight = 6
[[menu.main]]
    name = "  "
    url = "//"
    weight = 7
[[menu.main]]
    name = "问题反馈"
    url = "https://docs.qq.com/form/fill/DV0hma3JabFdya0Z4?isCreator=1#/fill"
    weight = 8
[[menu.main]]
    name = "版权"
    url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    weight = 9

[params]
# 千秋邈矣独留我，百战归来再读书
    description = "k12普惠教育推动及践行者"
    footer = "&copy; [Pengfei Zhang](https://pfzhang.com) 2017 - 2019 [Twitter](https://twitter.com/aisongshu) | [微博](http://weibo.com/6885419967) | [微信](../2018-10-30_095413.jpg)"

    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]

    # 加一段
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
    dateFormat = "2006-01-02" # "2006-01-02, Mon, "

#[[menu.main]]
#    name = "简历"
#    url = "/个人简历-张鹏飞-20180822.html"
#    weight = 3