baseurl = "/"
languageCode = "en-us"
title = "张鹏飞"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "留言"
    url = "/Zguestbook/"
    weight = 5
[[menu.main]]
    name = "行程"
    url = "/个人行程/"
    weight = 6

[params]
# 千秋邈矣独留我，百战归来再读书
	description = "在路上，永远年轻，永远热泪盈眶"
    footer = "&copy;  [Pengfei Zhang](https://pfzhang.com) 2013 -- 2018. All Rights Reserved"

#[[menu.main]]
#    name = "简历"
#    url = "/个人简历-张鹏飞-20180822.html"
#    weight = 3